ln -s fruit_and_vegetables/apple 0
ln -s fish/aquarium_fish 1
ln -s people/baby 2
ln -s large_carnivores/bear 3
ln -s aquatic_mammals/beaver 4
ln -s household_furniture/bed 5
ln -s insects/bee 6
ln -s insects/beetle 7
ln -s vehicles_1/bicycle 8
ln -s food_containers/bottle 9
ln -s food_containers/bowl 10
ln -s people/boy 11
ln -s large_man-made_outdoor_things/bridge 12
ln -s vehicles_1/bus 13
ln -s insects/butterfly 14
ln -s large_omnivores_and_herbivores/camel 15
ln -s food_containers/can 16
ln -s large_man-made_outdoor_things/castle 17
ln -s insects/caterpillar 18
ln -s large_omnivores_and_herbivores/cattle 19
ln -s household_furniture/chair 20
ln -s large_omnivores_and_herbivores/chimpanzee 21
ln -s household_electrical_devices/clock 22
ln -s large_natural_outdoor_scenes/cloud 23
ln -s insects/cockroach 24
ln -s household_furniture/couch 25
ln -s non-insect_invertebrates/crab 26
ln -s reptiles/crocodile 27
ln -s food_containers/cup 28
ln -s reptiles/dinosaur 29
ln -s aquatic_mammals/dolphin 30
ln -s large_omnivores_and_herbivores/elephant 31
ln -s fish/flatfish 32
ln -s large_natural_outdoor_scenes/forest 33
ln -s medium_mammals/fox 34
ln -s people/girl 35
ln -s small_mammals/hamster 36
ln -s large_man-made_outdoor_things/house 37
ln -s large_omnivores_and_herbivores/kangaroo 38
ln -s household_electrical_devices/keyboard 39
ln -s household_electrical_devices/lamp 40
ln -s vehicles_2/lawn_mower 41
ln -s large_carnivores/leopard 42
ln -s large_carnivores/lion 43
ln -s reptiles/lizard 44
ln -s non-insect_invertebrates/lobster 45
ln -s people/man 46
ln -s trees/maple_tree 47
ln -s vehicles_1/motorcycle 48
ln -s large_natural_outdoor_scenes/mountain 49
ln -s small_mammals/mouse 50
ln -s fruit_and_vegetables/mushroom 51
ln -s trees/oak_tree 52
ln -s fruit_and_vegetables/orange 53
ln -s flowers/orchid 54
ln -s aquatic_mammals/otter 55
ln -s trees/palm_tree 56
ln -s fruit_and_vegetables/pear 57
ln -s vehicles_1/pickup_truck 58
ln -s trees/pine_tree 59
ln -s large_natural_outdoor_scenes/plain 60
ln -s food_containers/plate 61
ln -s flowers/poppy 62
ln -s medium_mammals/porcupine 63
ln -s medium_mammals/possum 64
ln -s small_mammals/rabbit 65
ln -s medium_mammals/raccoon 66
ln -s fish/ray 67
ln -s large_man-made_outdoor_things/road 68
ln -s vehicles_2/rocket 69
ln -s flowers/rose 70
ln -s large_natural_outdoor_scenes/sea 71
ln -s aquatic_mammals/seal 72
ln -s fish/shark 73
ln -s small_mammals/shrew 74
ln -s medium_mammals/skunk 75
ln -s large_man-made_outdoor_things/skyscraper 76
ln -s non-insect_invertebrates/snail 77
ln -s reptiles/snake 78
ln -s non-insect_invertebrates/spider 79
ln -s small_mammals/squirrel 80
ln -s vehicles_2/streetcar 81
ln -s flowers/sunflower 82
ln -s fruit_and_vegetables/sweet_pepper 83
ln -s household_furniture/table 84
ln -s vehicles_2/tank 85
ln -s household_electrical_devices/telephone 86
ln -s household_electrical_devices/television 87
ln -s large_carnivores/tiger 88
ln -s vehicles_2/tractor 89
ln -s vehicles_1/train 90
ln -s fish/trout 91
ln -s flowers/tulip 92
ln -s reptiles/turtle 93
ln -s household_furniture/wardrobe 94
ln -s aquatic_mammals/whale 95
ln -s trees/willow_tree 96
ln -s large_carnivores/wolf 97
ln -s people/woman 98
ln -s non-insect_invertebrates/worm 99
